import Head from "next/head";
import Image from "next/image";
import { Gluten } from "@next/font/google";
import styles from "../styles/Home.module.css";
import Link from "next/link";

const gluten = Gluten({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>React Hooks Examples</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <p className={gluten.className}>Hello Next</p>
        <Image
          className={styles.logo}
          src="/next.svg"
          alt="Next.js Logo"
          width={180}
          height={37}
          priority
        />
        <button>
          <Link href="/search">Google Search</Link>
        </button>
      </main>
    </>
  );
}
